### ISSUE TITLE
Choose technologies

### ISSUE THREAD

**Issue by hkakutalua** [gdgluanda/rapidinho#2]
Discuss and choose technologies and infrastructure for the project

What was already choosed:
- Mobile Development Language and Framework (Dart and Flutter) ✅

What kind of tech/libraries we need to choose:
- Backend technology (Parse, Firebase, etc) for authentication and storage 🖥
- Networking 🌍 
- Local storage 💾 
- Device location fetching
- Geocoding 🌐
- Places Library 🗺 

It will be very useful if we use an architectural pattern like MVC or MVVM to keep the code maintainable through time.

**Comment by hkakutalua** [comment]
I can safely assume by now that using Flutter is agreed between us.
But we're going to need a backend technology, for now, my suggestion is using Firebase to handle authentication and storage.

We can also use Google Maps (and its equivalent Flutter libraries).

**Comment by pedromassango** [comment]
My Suggestion:

Flutter
Firebase (Auth, Database, Crashreport)
... others

**Comment by hkakutalua** [comment]
Thanks @pedromassango.

As i recall, we're all kind of used to working with Firebase, so that's a plus.

Other suggestions:
- Google Geocoding API: to reverse geocode world coordinates (Example: converting "lat:-8.922412, longitude: 13.364606" to Rua 11 de Novembro)
- Google Places API (to get places details)
- Google Location (To get user current location if needed)

I will edit the issue to include what type of libraries and technologies we would need in the app.
You can edit as well if needed.

**Comment by braulio94** [comment]
Greetings everyone.

I have somethings to clear up. 

  - It's important to know that we a not actually building a fully functional delivery application, the goal of this was to see what we can do we Flutter.
  - I believe have higher priorities in our lives and this app is not one of them because we're not getting paid for it.
  - Describing all of the functions that the app should have will just be overwhelming and no one will want to develop such functionalities.
   - I suggest we start with designing the user interface, doing whatever pleases us and we keep only what we all agree upon. 
   - We should use this project for fun.
   - Most of the features described above aren't actually implementable yet (especially maps)
   - Flutter has its own set of architectural patterns, I believe MVVM is not one of them, such as Redux, BloC, etc (please refer to [this for more](https://github.com/brianegan/flutter_architecture_samples)).
   - Let's start where we are and keep improving as we go. 

Nice emojis though ☺️

**Comment by hkakutalua** [comment]
I'm really good at overthinking things, now i see i got myself far ahead 😸.
So for now, and agreeing with you, let's just:
- Select few essential functionalities ([issue 1](https://github.com/gdgluanda/rapidinho/issues/1))
- Design the user interface
- Start coding the UI
- Implement functionalities

What do you guys thinks.

**Comment by braulio94** [comment]
Please let's not get ahead of ourselves.
Rather we create something, than nothing at all.

I agree with all above except **Design the user interface**. No one has time for that. 
Let's get inspiration from [uplabs](https://www.uplabs.com)

I'm going to create some more issues for **'Select few essential functionalities'**

**Comment by hkakutalua** [comment]
So, with everything said, let me 🔒 this
